# Cache
DEF_CACHE_SIZE 		= 50
DEF_CACHE_TIMEOUT 	= 120

# Probing
DEF_PROBE_TIME 		= 10

# Sleep times
DEF_SLEEP_TIME 		= 1
SLEEP_LEVEL_1 		= 2
SLEEP_LEVEL_2 		= 3
SLEEP_LEVEL_3 		= 4
SLEEP_LEVEL_4 		= 5